#define CRIT_EXTRAS_H

const char *lines[] = {

" and really hurts"
". A serious wound is inflicted"
". The damaging attack knocks him unconscious"
". The blow knocks him to the ground"
      ". The strong blow to the head knocks him out"
", death is instantaneous"
    ", pushing the arm out of the way"
", leaving a big bruise"
    ", crippling the left arm"
    ", leaving the left arm dangling by the skin"
    ". That arm now looks like a bloody stump"
    ", leaving a crippled right arm"
    ". His right arm is pulverized by this powerful blow"
    " in a forceful blow"
" blowing through the armor"
", inflicting an extra helping of damage"
" with no armor, knocking the combatant to the ground"
" knocking the air out, he slumps to the ground out of the fight"
    ". Unfortunately, his spine is now clearly visible from the front"
    " putting a major hurt on his leg"
", knocking him to the ground like a bowling pin in a league game"
    ", bowling him over and crippling that leg"
" inflicting some extra pain"
    " causing blindness, unluckily for him"
    ", and blinding him with a stunning blow"
    ". The loss of an eye is too much for him, and he falls to the ground"
", sadly, he is too busy feeling the rush of air on the brain to notice death approaching"
    ". Ouch! That had to hurt"
    ", and he's not wearing a cup, either"
    " and without protection, he falls over, groaning in agony"
". The pain is too much for him and he collapses like a rag"
". He mumbles \"Mother\", as his eyes roll into the back of his head"

"  You'll have a headache tomorrow, if you live that long"
". Your armor provides no protection from this well-aimed blow"
". You feel the pain for just a moment, and then darkness takes you.."
", bypassing your armor. The blow knocks you off your feet"
", the shock makes your vision go dark. After a moment, you notice that your vision has not returned"
". You get a nice view of your body as your head sails through the air"
". Surprisingly, the damage feels no worse than normal"
", stunning you for a moment"
". Feel the pain"
". The attack leaves your arm useless"
", slipping past your armor. The blow cracks the bones in your arm like deadwood"
", bypassing your armor. Your arm now hangs limply at your side"
". The bruise will look nice, and maybe the scars will make good party talk"
", crushing your internal organs. All you can do is gurgle blood"
", sending head over heels"
", sending you flying and breaking your leg"
", melting through your armor. The blow knocks you over and seriously hurts your knee"
". The pain from your broken leg sends you into unconsciousness"
". The painful blow makes you flinch, but does little else"
". Unlucky for you, it also causes immediate vision loss"
". It takes you a moment to wipe the blood from your eyes"
", slipping past your armor. You stand stunned as your realize you cannot see anymore"
". You feel a strange sensation in your head. You realize it's imminent brain-death"
", making you cringe"
". You cup your groin and fall to the floor in pain"
". The pain is sufficient to knock you out. Ouch"
". There are not enough words in the universe to describe the pain your are feeling at this moment"

}

#define num_lines = (sizeof(lines) / sizeof(lines[0]))
